name: Production C.I

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout action node
    - uses: actions/checkout@v3
    
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Deploy
    - run: |
        npm install
        npm run build
        npm run preview
